apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-slave
  labels:
    app: mysql-master-slave
data:
  # 这里使用ConfigMap保存mysql的配置文件
  master.cnf: |
    # 主节点 MySQL 的配置文件
    [mysqld]
    log-bin  # 开启log-bin
  slave.cnf: |
    # 从节点 MySQL 的配置文件
    [mysqld]
    super-read-only  # 除了来自主节点的数据同步,其他写均拒绝
