/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	txzdatahubv1 "datahub.txzing.com/mysql-gr-operator/pkg/apis/txz_datahub/v1"
	versioned "datahub.txzing.com/mysql-gr-operator/pkg/client/clientset/versioned"
	internalinterfaces "datahub.txzing.com/mysql-gr-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "datahub.txzing.com/mysql-gr-operator/pkg/client/listers/txz_datahub/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MysqlGROperatorInformer provides access to a shared informer and lister for
// MysqlGROperators.
type MysqlGROperatorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MysqlGROperatorLister
}

type mysqlGROperatorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMysqlGROperatorInformer constructs a new informer for MysqlGROperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMysqlGROperatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMysqlGROperatorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMysqlGROperatorInformer constructs a new informer for MysqlGROperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMysqlGROperatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatahubV1().MysqlGROperators(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatahubV1().MysqlGROperators(namespace).Watch(options)
			},
		},
		&txzdatahubv1.MysqlGROperator{},
		resyncPeriod,
		indexers,
	)
}

func (f *mysqlGROperatorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMysqlGROperatorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mysqlGROperatorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&txzdatahubv1.MysqlGROperator{}, f.defaultInformer)
}

func (f *mysqlGROperatorInformer) Lister() v1.MysqlGROperatorLister {
	return v1.NewMysqlGROperatorLister(f.Informer().GetIndexer())
}
