# 构建 spline 基本运行环境
version: '2'
services:
  spline-mongo:
    image: mongo:latest
    container_name: spline-mongo
    ports:
      - "27017:27017"

  spline-spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spline-spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spline-spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spline-spark-worker-1
    depends_on:
      - spline-spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data/:/home/data/
    environment:
      - "SPARK_MASTER=spark://spline-spark-master:7077"

  spline-web:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spline-web
    ports:
      - "8088:8088"
    volumes:
      - ./jars/spline-web-0.3.9-exec-war.jar:/spline-web-0.3.9-exec-war.jar
    depends_on:
      - spline-mongo
    command:
      [
        /usr/bin/java, -jar, /spline-web-0.3.9-exec-war.jar,
        "-Dspline.mongodb.url=mongodb://spline-mongo:27017/lineage",
        "-Dspline.mode=REQUIRED",
        "-httpPort=8088"
      ]
