# 构建 redis sentinel 集群
version: '2'
services:
  redis-1:
    image: redis:latest
    container_name: redis-1
    ports:
      - "26379:6379"
      - "36379:27000"
    volumes:
      - ./cnf/redis-1/:/usr/local/etc/redis/:rw
      - ./start_up.sh:/usr/local/etc/redis/start_up.sh
      - ./data/redis-1/:/data
    command: [/bin/bash, /usr/local/etc/redis/start_up.sh]

  redis-2:
    image: redis:latest
    container_name: redis-2
    ports:
      - "26380:6379"
      - "36380:27000"
    volumes:
      - ./cnf/redis-2/:/usr/local/etc/redis/:rw
      - ./start_up.sh:/usr/local/etc/redis/start_up.sh
      - ./data/redis-2/:/data
    depends_on:
      - redis-1
    command: [/bin/bash, /usr/local/etc/redis/start_up.sh]

  redis-3:
    image: redis:latest
    container_name: redis-3
    ports:
      - "26381:6379"
      - "36381:27000"
    volumes:
      - ./cnf/redis-3/:/usr/local/etc/redis/:rw
      - ./start_up.sh:/usr/local/etc/redis/start_up.sh
      - ./data/redis-3/:/data
    depends_on:
      - redis-1
    command: [/bin/bash, /usr/local/etc/redis/start_up.sh]
