apiVersion: apiextensions.k8s.io/v1beta1  # 使用的API
kind: CustomResourceDefinition
metadata:
  name: mysqlgroperators.datahub.txzing.com  # 必须是 plural + group 的形式
spec:
  group: datahub.txzing.com
  version: v1
  scope: Namespaced  # 属于Namespace的对象
  names:
    kind: MysqlGROperator
    plural: mysqlgroperators # 复数形式, 必须为小写
